services:

  frontend:
    build: ./frontend
    container_name: docker-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - docker-network

  backend:
    build: ./backend
    container_name: docker-backend
    ports:
      - "5000:5000"
    depends_on:
      - database
    networks:
      - docker-network

  database:
    image: mysql:8.0
    container_name: docker-database
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: devopsdb
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - docker-network

volumes:
  mysql-data:

networks:
  docker-network:
    driver: bridge